In [2]:
# Dependicies
import pandas as pd
import numpy as np
from citipy import citipy

# Import file
seattle_df = pd.read_csv('SDOT_Collisions_-_All_Years.csv')
seattle_df.head(10)

,X,Y,OBJECTID,INCKEY,COLDETKEY,ADDRTYPE,COLLISIONTYPE,EXCEPTRSNCODE,EXCEPTRSNDESC,FATALITIES,...,ADDDTTM,MODBY,MODDTTM,ST_PARTCPNT_TYPE,ST_PARTCPNT_TYPE_DESC,ST_AGE,ST_CITED,ST_VEH_TYPE_CD,ST_VEH_TYPE_DESC,ST_INJRY_CLSS_DESC
0,1.271322e+06,217404.089923,1,335146,336646,Intersection,Right Turn,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.272086e+06,212007.295599,2,353750,355210,Block,Rear Ended,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.272384e+06,224370.589442,3,34300,34300,Block,Rear Ended,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.274204e+06,223012.329363,4,335066,336566,Intersection,Rear Ended,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.266010e+06,271489.407278,5,62100,62100,Block,Left Turn,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.264090e+06,229810.048051,6,1082,1082,Intersection,Left Turn,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.275587e+06,212337.728665,7,1255,1255,Block,Parked Car,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.284349e+06,205390.566050,8,76100,76100,Block,Parked Car,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.265055e+06,229784.721002,9,357107,358567,Intersection,Angles,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.265803e+06,269008.050364,10,1358,1358,Block,Left Turn,,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
seattle_df=seattle_df.drop[['INCKEY', 'OBJECTID', 'COLDETKEY', 'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'INCDTTM', 'INTKEY', 'JUNCTIONTYPE', 'Location','PEDROWNOTGRNT', 'REPORTNO', 'SDOT_COLDESC', 'SDOTCOLNUM', 'ST_COLDESC', 'STATUS', 'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR', 'SOURCEDESC', 'ADDDTTM','MODBY', 'MODDTTM', 'ST_PARTCPNT_TYPE', 'ST_PARTCPNT_TYPE_DESC', 'ST_AGE', 'ST_CITED', 'ST_VEH_TYPE_CD', 'ST_VEH_TYPE_DESC', 'ST_INJRY_CLSS_DESC'] axis=1]
seattle_df.head(10)

SyntaxError: invalid syntax (2809657425.py, line 1)

In [ ]:
# Drop columns
seattle_df = seattle_df.drop[seattle_df[]]